version: "3.9"

services:
  web:
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - node_modules:/app/node_modules
volumes:
  node_modules: